pipeline {
    agent any

    environment {
        DEV_REPO = "naliniselv/react-app-dev"
        PROD_REPO = "naliniselv/react-app-prod"
        EC2_IP = "54.160.167.129"
        CONTAINER_NAME = "react-app-container"
    }

    stages {

        stage('Checkout Repository') {
            steps {
                git branch: "${env.BRANCH_NAME}",
                    url: 'https://github.com/Nalini-0212/devopsjs.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image..."

                sh '''
                    chmod +x ./scripts/build.sh
                    ./scripts/build.sh
                '''
            }
        }

        stage('Docker Login') {
            steps {
                echo "Logging into Docker Hub..."

                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhubcred',
                        usernameVariable: 'DOCKERHUB_USERNAME',
                        passwordVariable: 'DOCKERHUB_PASSWORD'
                    )
                ]) {

                    sh '''
                        echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {

                    if (env.BRANCH_NAME == 'dev') {

                        sh '''
                            echo "Pushing image to DEV repository..."

                            docker tag react-app:latest $DEV_REPO:$BUILD_NUMBER
                            docker tag react-app:latest $DEV_REPO:latest

                            docker push $DEV_REPO:$BUILD_NUMBER
                            docker push $DEV_REPO:latest
                        '''

                    } else if (env.BRANCH_NAME == 'main') {

                        sh '''
                            echo "Pushing image to PROD repository..."

                            docker tag react-app:latest $PROD_REPO:$BUILD_NUMBER
                            docker tag react-app:latest $PROD_REPO:latest

                            docker push $PROD_REPO:$BUILD_NUMBER
                            docker push $PROD_REPO:latest
                        '''

                    } else {

                        echo "Skipping Docker push for branch: ${env.BRANCH_NAME}"

                    }
                }
            }
        }

    }

    post {

        success {
            echo "Build and Docker push completed successfully."
        }

        failure {
            echo "Build or push failed."
        }

        always {
            echo "Cleaning up..."
            sh """
            docker logout || true
            docker image prune -f || true //remove dangling images
            docker container prune -f || true //remove stopped containers
            docker rmi -f react-app:latest || true //remove local image with latest tag
            docker rmi -f $DEV_REPO:latest || true //remove dev latest image
            docker rmi -f $DEV_REPO:$BUILD_NUMBER || true //remove dev build number image
            docker rmi -f $PROD_REPO:latest || true //remove prod latest image
            docker rmi -f $PROD_REPO:$BUILD_NUMBER || true //remove prod build number image
            cleanWs() //clean workspace
            """
        }
    }
}